import uuid from 'uuid/v4';

// dummy data
export const data = [
  {
    id: uuid(),
    barcode: '',
    productName: 'Quellbrunn',
    amount: 6,
    customNote: 'lorem ipsum',
    productCategory: 'drinks',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-06',
    pushNotificationDate: '2019-12-01',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Mandarinen',
    amount: 12,
    customNote: 'lorem ipsum',
    productCategory: 'fruits',
    addedDate: '2019-09-03',
    bestBeforeDate: '2020-11-23',
    pushNotificationDate: '2019-11-11',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Ehrmann Almighurt',
    amount: 4,
    customNote: '',
    productCategory: 'dairy',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-11-04',
    pushNotificationDate: '2019-11-03',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Exquisa Frischkäse',
    amount: 1,
    customNote: 'lorem ipsum',
    productCategory: 'dairy',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-08-30',
    pushNotificationDate: '2019-08-29',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Bio Hanfblüten-Tee',
    amount: '25g',
    customNote: 'lorem ipsum',
    productCategory: 'drinks',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-24',
    pushNotificationDate: '2019-12-23',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'dmBio Kichererbsen',
    amount: '200g',
    customNote: 'lorem ipsum',
    productCategory: 'canned',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-01',
    pushNotificationDate: '2019-12-01',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Oreo Golden',
    amount: '154g',
    customNote: 'lorem ipsum',
    productCategory: 'snacks',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-02',
    pushNotificationDate: '2019-12-02',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Rinderhackfleisch',
    amount: '500g',
    customNote: 'lorem ipsum',
    productCategory: 'frozen',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-03',
    pushNotificationDate: '2019-12-03',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Pesto Basilico',
    amount: '190g',
    customNote: 'lorem ipsum',
    productCategory: 'canned',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-04',
    pushNotificationDate: '2019-12-04',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Brot',
    amount: 1,
    customNote: 'lorem ipsum',
    productCategory: 'bread',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-05',
    pushNotificationDate: '2019-12-05',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Brot',
    amount: 1,
    customNote: 'lorem ipsum',
    productCategory: 'bread',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-05',
    pushNotificationDate: '2019-12-05',
  },
];
