import uuid from 'uuid/v4';

// dummy data
export const data = [
  {
    id: uuid(),
    barcode: '',
    productName: 'Quellbrunn',
    amount: 6,
    customNote: 'lorem ipsum',
    productCategory: 'drinks',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-06',
    pushNotificationDate: '2019-12-01',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Mandarinen',
    amount: 12,
    customNote: 'lorem ipsum',
    productCategory: 'fruits',
    addedDate: '2019-09-03',
    bestBeforeDate: '2020-11-23',
    pushNotificationDate: '2019-11-11',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Bananen',
    amount: 10,
    customNote: 'lorem ipsum',
    productCategory: 'fruits',
    addedDate: '2019-10-01',
    bestBeforeDate: '2019-10-23',
    pushNotificationDate: '2019-10-20',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Himberen',
    amount: '200g',
    customNote: 'lorem ipsum',
    productCategory: 'fruits',
    addedDate: '2019-10-02',
    bestBeforeDate: '2019-10-07',
    pushNotificationDate: '2019-10-05',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Karotten',
    amount: '1kg',
    customNote: 'lorem ipsum',
    productCategory: 'fruits',
    addedDate: '2019-09-30',
    bestBeforeDate: '2019-10-10',
    pushNotificationDate: '2019-10-07',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Paprika Rot',
    amount: '500g',
    customNote: 'lorem ipsum',
    productCategory: 'fruits',
    addedDate: '2019-09-30',
    bestBeforeDate: '2019-10-05',
    pushNotificationDate: '2019-10-03',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Ehrmann Almighurt',
    amount: 4,
    customNote: '',
    productCategory: 'dairy',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-11-04',
    pushNotificationDate: '2019-11-03',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Exquisa Frischkäse',
    amount: 1,
    customNote: 'lorem ipsum',
    productCategory: 'dairy',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-08-30',
    pushNotificationDate: '2019-08-29',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Eier',
    amount: 12,
    customNote: 'lorem ipsum',
    productCategory: 'dairy',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-09-30',
    pushNotificationDate: '2019-09-24',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Milch',
    amount: 1,
    customNote: 'lorem ipsum',
    productCategory: 'dairy',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-10-30',
    pushNotificationDate: '2019-09-24',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Bio Hanfblüten-Tee',
    amount: '25g',
    customNote: 'lorem ipsum',
    productCategory: 'drinks',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-24',
    pushNotificationDate: '2019-12-23',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'dmBio Kichererbsen',
    amount: '200g',
    customNote: 'lorem ipsum',
    productCategory: 'canned',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-01',
    pushNotificationDate: '2019-12-01',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'REWE Beste Wahl Baked Beans in Tomatensoße',
    amount: '420g',
    customNote: 'lorem ipsum',
    productCategory: 'canned',
    addedDate: '2019-08-03',
    bestBeforeDate: '2020-05-01',
    pushNotificationDate: '2020-04-25',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Oreo Golden',
    amount: '154g',
    customNote: 'lorem ipsum',
    productCategory: 'snacks',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-02',
    pushNotificationDate: '2019-12-02',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Rinderhackfleisch',
    amount: '500g',
    customNote: 'lorem ipsum',
    productCategory: 'frozen',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-03',
    pushNotificationDate: '2019-12-03',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Pesto Basilico',
    amount: '190g',
    customNote: 'lorem ipsum',
    productCategory: 'canned',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-04',
    pushNotificationDate: '2019-12-04',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Brot',
    amount: 1,
    customNote: 'lorem ipsum',
    productCategory: 'bread',
    addedDate: '2019-09-03',
    bestBeforeDate: '2019-12-05',
    pushNotificationDate: '2019-12-05',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Brötchen',
    amount: 4,
    customNote: 'lorem ipsum',
    productCategory: 'bread',
    addedDate: '2019-10-02',
    bestBeforeDate: '2019-10-25',
    pushNotificationDate: '2019-10-02',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Pombär Original',
    amount: 2,
    customNote: 'lorem ipsum',
    productCategory: 'snacks',
    addedDate: '2019-10-02',
    bestBeforeDate: '2020-05-29',
    pushNotificationDate: '2020-05-20',
  },
  {
    id: uuid(),
    barcode: '',
    productName: 'Ritter Sport Dunkle Vollnuss',
    amount: 5,
    customNote: 'lorem ipsum',
    productCategory: 'snacks',
    addedDate: '2019-10-02',
    bestBeforeDate: '2019-11-29',
    pushNotificationDate: '2019-11-20',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Haribo Tropifrutti',
    amount: '200g',
    customNote: 'lorem ipsum',
    productCategory: 'snacks',
    addedDate: '2019-10-02',
    bestBeforeDate: '2019-12-27',
    pushNotificationDate: '2019-12-20',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Lorenz Saltletts Brezel',
    amount: '200g',
    customNote: 'lorem ipsum',
    productCategory: 'snacks',
    addedDate: '2019-10-01',
    bestBeforeDate: '2019-11-20',
    pushNotificationDate: '2019-11-15',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Milka Tafel Ganze Haselnüsse',
    amount: '100g',
    customNote: 'lorem ipsum',
    productCategory: 'snacks',
    addedDate: '2019-10-01',
    bestBeforeDate: '2019-11-20',
    pushNotificationDate: '2019-11-15',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Pringles Original',
    amount: '200g',
    customNote: 'lorem ipsum',
    productCategory: 'snacks',
    addedDate: '2019-10-01',
    bestBeforeDate: '2019-11-20',
    pushNotificationDate: '2019-11-15',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Ültje Erdnüsse ohne Fett',
    amount: '190g',
    customNote: 'lorem ipsum',
    productCategory: 'snacks',
    addedDate: '2019-10-01',
    bestBeforeDate: '2019-11-20',
    pushNotificationDate: '2019-11-15',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Funny Frisch Linsenchips Paprika',
    amount: '90g',
    customNote: 'lorem ipsum',
    productCategory: 'snacks',
    addedDate: '2019-10-01',
    bestBeforeDate: '2019-12-20',
    pushNotificationDate: '2019-12-15',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Dinkel Max Bio Dinkelvollkorn Spiralen',
    amount: '200g',
    customNote: 'lorem ipsum',
    productCategory: 'pasta',
    addedDate: '2019-07-03',
    bestBeforeDate: '2020-03-03',
    pushNotificationDate: '2020-02-27',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Probios Bio Conchiglie Maisnudeln glutenfrei',
    amount: '400g',
    customNote: 'lorem ipsum',
    productCategory: 'pasta',
    addedDate: '2019-08-25',
    bestBeforeDate: '2020-04-04',
    pushNotificationDate: '2020-04-28',
  },

  {
    id: uuid(),
    barcode: '',
    productName: 'Bauck Hof Bio Mehl-Mix Kuchen',
    amount: '800g',
    customNote: 'lorem ipsum',
    productCategory: 'pasta',
    addedDate: '2019-09-20',
    bestBeforeDate: '2020-04-13',
    pushNotificationDate: '2020-04-05',
  },
];
